### ISSUE TITLE
Page Link Spawning

### ISSUE THREAD

**Issue by Cattista** [cpcnewhaven/cpcnewhaven.github.io#1]
On the Podcasts page (https://cpcnewhaven.org/podcasts.html) if you click a page number that doesn't match the current page number, the website will refresh, adding an additional page selection menu.

![image](https://github.com/user-attachments/assets/6442274a-2365-4440-9c18-1150fad6e1e7)

**Comment by cpcnewhaven** [comment]
fixed (for now) - too out pagination for now - going to see about "infinite scroll"
