### ISSUE TITLE
Duplicate links for Ministries: Children

### ISSUE THREAD

**Issue by Cattista** [cpcnewhaven/cpcnewhaven.github.io#3]
Community>Ministries> Children & Children's Education

Are these supposed to be the same or separate items? The "Children" link works and goes to "Children's Christian Education" whereas the "Children's Education" link does not work.

![image](https://github.com/user-attachments/assets/235b0cb8-ac4b-4915-82c5-9e030f667d52)

**Comment by cpcnewhaven** [comment]
resolved
