### ISSUE TITLE
Footer Link

### ISSUE THREAD

**Issue by Cattista** [cpcnewhaven/cpcnewhaven.github.io#4]
The footer link on each page seems to open a new tab to the same page you are already on. Is this the intended behavior?

![image](https://github.com/user-attachments/assets/2daedfc0-f93d-4ef4-aa9f-1436b1b56d5e)

**Comment by cpcnewhaven** [comment]
hmm - can pipe it to index.html

**Comment by Cattista** [comment]
I assumed you meant to use "/" instead of "#", but wasn't entirely sure. That should fix it.

**Comment by cpcnewhaven** [comment]
resolved - made it link to the homepage
