### ISSUE TITLE
Church Community Builder Link

### ISSUE THREAD

**Issue by Cattista** [cpcnewhaven/cpcnewhaven.github.io#5]
On the Resources page, there is a link to www.cpcnewhaven.org/church-community-builder which links to the page on the old website which links to https://cpcnewhaven.ccbchurch.com/login.php.

I had created a redirect for ccb.cpcnewhaven.org to our CCB login, but it may be possible to update CCB to actually use that domain instead of theirs. I don't have access to CCB, so you would need to check with Alexis.

![image](https://github.com/user-attachments/assets/55ee97f8-b3ea-4e5d-8f37-a9aacfb82fe4)

**Comment by cpcnewhaven** [comment]
thanks for doing this - linked it up in the sidebar - issue resolved
